name: 'Update docs'

on:
  repository_dispatch:
    types: [doc_changes]

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: 'yarn'
      - name: 'Download docs'
        run: 'yarn pre-build ${{ github.event.client_payload.sha }} ${{ github.event.client_payload.branch}}'
      - name: 'Push changes or create PR'
        run: 'yarn process-docs-changes'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
