name: 'Update docs'

on:
  repository_dispatch:
    types: [doc_changes_branches]

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: 'Switch branches'
# We switch to the version branch or create a new one if needed
        run: git checkout v$${{ github.event.client_payload.branch}} || git checkout -b v$${{ github.event.client_payload.branch}}
      - name: Install dependencies
        run: 'yarn'
      - name: 'Prebuild'
        run: 'yarn pre-build ${{ github.event.client_payload.sha }}'
      - name: 'Push changes or create PR'
        run: 'yarn process-docs-changes'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
